### ISSUE TITLE
AoC note

### ISSUE THREAD

**Issue by rasputyashka** [rasputyashka/jjm#8]
It is useful when you can specify output for several files like
```toml
[main]
in = "aBc"
[sol] # extension does not matter
out = "abc"
[sol2] # or it can take the config's languge extension
out = "ABC"
```
